import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "primary-fixed-dim": "#bec6e0",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        "surface-glass": "rgba(255, 255, 255, 0.7)",
        "mint-accent": "#E0F2F1",
        "on-surface-variant": "#45464d",
        "surface-bright": "#f8f9fa",
        "inverse-surface": "#2e3132",
        "on-background": "#191c1d",
        "secondary-fixed": "#9feffe",
        "on-secondary-fixed": "#001f24",
        "on-tertiary-fixed": "#221b02",
        "error-container": "#ffdad6",
        "gold-leaf": "#D4AF37",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-fixed-variant": "#004f59",
        primary: "#000000",
        "surface-dim": "#d9dadb",
        "surface-container-high": "#e7e8e9",
        "on-primary-fixed": "#131b2e",
        tertiary: "#695e3d",
        background: "#f8f9fa",
        "tertiary-fixed-dim": "#d5c69d",
        "on-tertiary-fixed-variant": "#504627",
        "on-tertiary-container": "#483f20",
        "on-primary-container": "#7c839b",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#bec6e0",
        outline: "#76777d",
        "tertiary-container": "#b8aa83",
        "surface-variant": "#e1e3e4",
        "text-muted": "#64748B",
        "surface-container": "#edeeef",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#565e74",
        "on-surface": "#191c1d",
        "on-secondary-container": "#016d7a",
        "on-error": "#ffffff",
        "primary-container": "#131b2e",
        surface: "#f8f9fa",
        "primary-fixed": "#dae2fd",
        "outline-variant": "#c6c6cd",
        "tertiary-fixed": "#f1e1b8",
        "secondary-container": "#9cecfb",
        "inverse-on-surface": "#f0f1f2",
        "secondary-fixed-dim": "#83d3e1",
        "on-primary-fixed-variant": "#3f465c",
        secondary: "#006875",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "section-margin": "48px",
        "container-padding": "32px",
        "card-gap": "20px",
        unit: "8px",
      },
      fontFamily: {
        sans: ["var(--font-jakarta)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
